### ISSUE TITLE
Karavan-Designer Build Issues

### ISSUE THREAD

**Issue by kondetiramanakumar** [apache/camel-karavan#1211] opened 2024-04-01 12:29 UTC
I am getting the source code Issues while building the karavan-desinger source in my local machine.
![image](https://github.com/apache/camel-karavan/assets/14121796/f8fcf5a7-5bb1-4f31-b070-25890de0da86)
![image](https://github.com/apache/camel-karavan/assets/14121796/e20af398-e46e-4f0f-bb1c-2f9387bbdd8d)

please help me out from this build issues?????

**Comment by davsclaus** [comment] 2024-04-02 04:39
duplicate of https://github.com/apache/camel-karavan/discussions/1198

**Closed by davsclaus** 2024-04-02 04:39 UTC
