### ISSUE TITLE
Caused by: java.lang.IllegalArgumentException: Cannot find RoutesBuilderLoader in classpath supporting file extension: javaCaused by: java.lang.IllegalArgumentException: Cannot find RoutesBuilderLoader in classpath supporting file extension: java

### ISSUE THREAD

**Issue by petrroda** [apache/camel-karavan#724] opened 2023-04-15 15:09 UTC
When running my own code but also the 

karavan-demo/rest-service)/quarkus/ 

with quarkus dev I get the 

Caused by: java.lang.IllegalArgumentException: Cannot find RoutesBuilderLoader in classpath supporting file extension: javaCaused by: java.lang.IllegalArgumentException: Cannot find RoutesBuilderLoader in classpath supporting file extension: java

**Comment by davsclaus** [comment] 2023-04-15 16:12
Yes if you export to quarkus then you may have that problem
https://issues.apache.org/jira/browse/CAMEL-19267

You can edit the file src/main/resources/application.properties, where mistakenly there is a line that says camel/xxx.java

**Comment by petrroda** [comment] 2023-04-18 07:13
Hi, 

I have the same behaviour with Camel K and an integration directory. How should the custom java files be placed within an Camel K integration directory?

Greets
Petr

**Comment by davsclaus** [comment] 2023-04-18 07:21
You need to ask in the camel-k chat room or their issue tracker
https://github.com/apache/camel-k

**Comment by davsclaus** [comment] 2023-04-18 07:22
And if you are using camel-jbang 3.20.3, then you can downgrade to 3.20.2 as it should work with exporting.
A new 3.20.4 release (fixed) is coming later this month.

**Comment by skumaravelan** [comment] 2023-11-02 18:19
: Error reloading routes due to Cannot find RoutesBuilderLoader in classpath supporting file extension: jkube.yaml. This exception is ignored.
java.lang.IllegalArgumentException: Cannot find RoutesBuilderLoader in classpath supporting file extension: jkube.yaml
	at org.apache.camel.impl.engine.DefaultRoutesLoader.resolveRoutesBuilderLoader(DefaultRoutesLoader.java:225) ~[camel-base-engine-4.0.0.jar:4.0.0]
	at org.apache.camel.impl.engine.DefaultRoutesLoader.findRoutesBuilders(DefaultRoutesLoader.java:99) ~[camel-base-engine-4.0.0.jar:4.0.0]
	at org.apache.camel.impl.engine.DefaultRoutesLoader.findRoutesBuilders(DefaultRoutesLoader.java:88) ~[camel-base-engine-4.0.0.jar:4.0.0]
	at org.apache.camel.impl.engine.DefaultRoutesLoader.updateRoutes(DefaultRoutesLoader.java:197) ~[camel-base-engine-4.0.0.jar:4.0.0]
	at org.apache.camel.support.RouteWatcherReloadStrategy.onRouteReload(RouteWatcherReloadStrategy.java:289) ~[camel-support-4.0.0.jar:4.0.0]
	at org.apache.camel.support.RouteOnDemandReloadStrategy.doOnReload(RouteOnDemandReloadStrategy.java:114) ~[camel-support-4.0.0.jar:4.0.0]
	at org.apache.camel.support.RouteOnDemandReloadStrategy.onReload(RouteOnDemandReloadStrategy.java:74) ~[camel-support-4.0.0.jar:4.0.0]
	at org.apache.camel.impl.console.ReloadDevConsole.lambda$doCallJson$1(ReloadDevConsole.java:71) ~[camel-console-4.0.0.jar:4.0.0]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539) [?:?]
	at java.util.concurrent.FutureTask.run(FutureTask.java:264) [?:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) [?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) [?:?]

**Comment by davsclaus** [comment] 2023-11-03 08:10
Yeah we should skip those files
https://issues.apache.org/jira/browse/CAMEL-20076

You can use --exclude to skip the files if you run Camel manually from terminal

**Comment by leandremucyo** [comment] 2023-12-20 22:01
Had a similar issue with a slightly different error : Caused by: java.lang.IllegalArgumentException: Cannot find RoutesBuilderLoader in classpath supporting file extension: **csv**

RoutesConfigurer showed the following log:
`Discovered 1 additional RoutesBuilder from registry: classpath:camel/*,classpath:camel-template/*,classpath:camel-rest/*`

In the test resources folder I have a subfolder named `camel` containing csv files, this folder was getting processed and the extension of csv gets picked up. Renaming the my folder to something else fixed the issue.

If the full path of those `jkube.yaml` is on classpath with camel/ or camel-template/ or camel-rest/  consider renaming it, after renaming the folder I had issue was fixed.

**Comment by davsclaus** [comment] 2024-05-18 19:18
closing old ticket

**Closed by davsclaus** 2024-05-18 19:18 UTC

**Comment by njiddasalifu** [comment] 2024-06-05 20:17
hello @davsclaus i am facing a similar in running an integration project i am working using camel.
