### ISSUE TITLE
Select step tab not readable

### ISSUE THREAD

**Issue by Croway** [apache/camel-karavan#62] opened 2021-11-02 10:36 UTC
When following `Development Karavan app` the Select step modal is
![image](https://user-images.githubusercontent.com/34543311/139830994-54e435b8-37fc-4a7f-b85b-e3d185ba669a.png)

**Comment by mgubaidullin** [comment] 2021-11-02 11:37
Duplicate of #40

**Comment by mgubaidullin** [comment] 2021-11-02 11:38
Fixed. Will be available in next preview

**Closed by mgubaidullin** 2021-11-02 11:38 UTC

**Comment by Croway** [comment] 2021-11-02 11:45
Hi @mgubaidullin, I'm sorry, I didn't notice the other issue!, btw in order to build the project I had to do some changes to codebase, in particular I had to edit some tsx files

- in DesignerPage I had to add dark={true] to KaravanDesigner tag
- in Kamelet* I had to rename the import `import {Kamelet} from "../designer/model/KameletModels";` to `import {KameletModel} from "../designer/model/KameletModels";` 

do you want me to open issues or PRs ?

**Comment by mgubaidullin** [comment] 2021-11-02 13:11
@Croway 
Do you have issues with karavan-app? if yes, it would be great if you fix this issues and make a PR.
However I would prefer dark={false} in KaravanDesigner for an karavan-app, because web version of Karavan has only light mode.
